name: Build iOS Application

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Generate iOS Project
        run: flutter create --platforms=ios .

      - name: Patch Info.plist
        run: |
          P=ios/Runner/Info.plist
          /usr/libexec/PlistBuddy -c "Add :NSAppTransportSecurity dict" $P
          /usr/libexec/PlistBuddy -c "Add :NSAppTransportSecurity:NSAllowsArbitraryLoads bool true" $P
          /usr/libexec/PlistBuddy -c "Add :NSLocalNetworkUsageDescription string 'Needed to send PKG files to PS4'" $P

      - name: Install Dependencies
        run: flutter pub get

      - name: Build iOS Application (No Codesign)
        run: flutter build ios --release --no-codesign

      - name: Package Payload folder for TIPA/IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -r PS4_PKG_Tool_iOS.ipa Payload

      - name: Upload iOS Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PS4_PKG_Tool_iOS_Build
          path: build/ios/iphoneos/PS4_PKG_Tool_iOS.ipa
